// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getAnswer = `-- name: GetAnswer :one
SELECT id, game_id, question_id, player_id, answer, is_correct, points_awarded, submitted_at FROM answers
WHERE game_id = $1
  AND question_id = $2
  AND player_id = $3
`

type GetAnswerParams struct {
	GameID     uuid.UUID `json:"game_id"`
	QuestionID uuid.UUID `json:"question_id"`
	PlayerID   uuid.UUID `json:"player_id"`
}

func (q *Queries) GetAnswer(ctx context.Context, arg GetAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, getAnswer, arg.GameID, arg.QuestionID, arg.PlayerID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.PlayerID,
		&i.Answer,
		&i.IsCorrect,
		&i.PointsAwarded,
		&i.SubmittedAt,
	)
	return i, err
}

const listAnswersForGame = `-- name: ListAnswersForGame :many
SELECT id, game_id, question_id, player_id, answer, is_correct, points_awarded, submitted_at FROM answers
WHERE game_id = $1
ORDER BY submitted_at ASC
`

func (q *Queries) ListAnswersForGame(ctx context.Context, gameID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.QuestionID,
			&i.PlayerID,
			&i.Answer,
			&i.IsCorrect,
			&i.PointsAwarded,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersForPlayer = `-- name: ListAnswersForPlayer :many
SELECT id, game_id, question_id, player_id, answer, is_correct, points_awarded, submitted_at FROM answers
WHERE player_id = $1
ORDER BY submitted_at ASC
`

func (q *Queries) ListAnswersForPlayer(ctx context.Context, playerID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.QuestionID,
			&i.PlayerID,
			&i.Answer,
			&i.IsCorrect,
			&i.PointsAwarded,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersForQuestion = `-- name: ListAnswersForQuestion :many
SELECT id, game_id, question_id, player_id, answer, is_correct, points_awarded, submitted_at FROM answers
WHERE game_id = $1
  AND question_id = $2
ORDER BY submitted_at ASC
`

type ListAnswersForQuestionParams struct {
	GameID     uuid.UUID `json:"game_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) ListAnswersForQuestion(ctx context.Context, arg ListAnswersForQuestionParams) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersForQuestion, arg.GameID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Answer{}
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.QuestionID,
			&i.PlayerID,
			&i.Answer,
			&i.IsCorrect,
			&i.PointsAwarded,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAnswer = `-- name: RecordAnswer :one
INSERT INTO answers (id, game_id, question_id, player_id, answer, is_correct, points_awarded)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, game_id, question_id, player_id, answer, is_correct, points_awarded, submitted_at
`

type RecordAnswerParams struct {
	ID            uuid.UUID `json:"id"`
	GameID        uuid.UUID `json:"game_id"`
	QuestionID    uuid.UUID `json:"question_id"`
	PlayerID      uuid.UUID `json:"player_id"`
	Answer        string    `json:"answer"`
	IsCorrect     bool      `json:"is_correct"`
	PointsAwarded int32     `json:"points_awarded"`
}

func (q *Queries) RecordAnswer(ctx context.Context, arg RecordAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, recordAnswer,
		arg.ID,
		arg.GameID,
		arg.QuestionID,
		arg.PlayerID,
		arg.Answer,
		arg.IsCorrect,
		arg.PointsAwarded,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.PlayerID,
		&i.Answer,
		&i.IsCorrect,
		&i.PointsAwarded,
		&i.SubmittedAt,
	)
	return i, err
}
