// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question_banks.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestionBank = `-- name: CreateQuestionBank :one
INSERT INTO question_banks (id, owner_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, description, created_at, updated_at
`

type CreateQuestionBankParams struct {
	ID          uuid.UUID   `json:"id"`
	OwnerID     uuid.UUID   `json:"owner_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateQuestionBank(ctx context.Context, arg CreateQuestionBankParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, createQuestionBank,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
	)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestionBank = `-- name: DeleteQuestionBank :exec
DELETE FROM question_banks WHERE id = $1
`

func (q *Queries) DeleteQuestionBank(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionBank, id)
	return err
}

const getQuestionBank = `-- name: GetQuestionBank :one
SELECT id, owner_id, name, description, created_at, updated_at FROM question_banks WHERE id = $1
`

func (q *Queries) GetQuestionBank(ctx context.Context, id uuid.UUID) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, getQuestionBank, id)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestionBanksByOwner = `-- name: ListQuestionBanksByOwner :many
SELECT id, owner_id, name, description, created_at, updated_at FROM question_banks
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListQuestionBanksByOwner(ctx context.Context, ownerID uuid.UUID) ([]QuestionBank, error) {
	rows, err := q.db.Query(ctx, listQuestionBanksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuestionBank{}
	for rows.Next() {
		var i QuestionBank
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionBank = `-- name: UpdateQuestionBank :one
UPDATE question_banks
SET name        = $2,
    description = $3
WHERE id = $1
RETURNING id, owner_id, name, description, created_at, updated_at
`

type UpdateQuestionBankParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateQuestionBank(ctx context.Context, arg UpdateQuestionBankParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, updateQuestionBank, arg.ID, arg.Name, arg.Description)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
