// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countQuestionsInBank = `-- name: CountQuestionsInBank :one
SELECT COUNT(*)::int AS count FROM questions WHERE bank_id = $1
`

func (q *Queries) CountQuestionsInBank(ctx context.Context, bankID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countQuestionsInBank, bankID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (id, bank_id, type, prompt, correct_answer, choices, points, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, bank_id, type, prompt, correct_answer, choices, points, position, created_at, updated_at
`

type CreateQuestionParams struct {
	ID            uuid.UUID    `json:"id"`
	BankID        uuid.UUID    `json:"bank_id"`
	Type          QuestionType `json:"type"`
	Prompt        string       `json:"prompt"`
	CorrectAnswer string       `json:"correct_answer"`
	Choices       []byte       `json:"choices"`
	Points        int32        `json:"points"`
	Position      int32        `json:"position"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ID,
		arg.BankID,
		arg.Type,
		arg.Prompt,
		arg.CorrectAnswer,
		arg.Choices,
		arg.Points,
		arg.Position,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Type,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.Choices,
		&i.Points,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, bank_id, type, prompt, correct_answer, choices, points, position, created_at, updated_at FROM questions WHERE id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Type,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.Choices,
		&i.Points,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestionsByBank = `-- name: ListQuestionsByBank :many
SELECT id, bank_id, type, prompt, correct_answer, choices, points, position, created_at, updated_at FROM questions
WHERE bank_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListQuestionsByBank(ctx context.Context, bankID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByBank, bankID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.BankID,
			&i.Type,
			&i.Prompt,
			&i.CorrectAnswer,
			&i.Choices,
			&i.Points,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderQuestion = `-- name: ReorderQuestion :one
UPDATE questions
SET position = $2
WHERE id = $1
RETURNING id, bank_id, type, prompt, correct_answer, choices, points, position, created_at, updated_at
`

type ReorderQuestionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) ReorderQuestion(ctx context.Context, arg ReorderQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, reorderQuestion, arg.ID, arg.Position)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Type,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.Choices,
		&i.Points,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET type           = $2,
    prompt         = $3,
    correct_answer = $4,
    choices        = $5,
    points         = $6,
    position       = $7
WHERE id = $1
RETURNING id, bank_id, type, prompt, correct_answer, choices, points, position, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID            uuid.UUID    `json:"id"`
	Type          QuestionType `json:"type"`
	Prompt        string       `json:"prompt"`
	CorrectAnswer string       `json:"correct_answer"`
	Choices       []byte       `json:"choices"`
	Points        int32        `json:"points"`
	Position      int32        `json:"position"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Type,
		arg.Prompt,
		arg.CorrectAnswer,
		arg.Choices,
		arg.Points,
		arg.Position,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.BankID,
		&i.Type,
		&i.Prompt,
		&i.CorrectAnswer,
		&i.Choices,
		&i.Points,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
