// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubscriptionByStripeSubID = `-- name: GetSubscriptionByStripeSubID :one
SELECT id, user_id, plan, status, current_period_end, stripe_customer_id, stripe_subscription_id, created_at, updated_at FROM subscriptions WHERE stripe_subscription_id = $1
`

func (q *Queries) GetSubscriptionByStripeSubID(ctx context.Context, stripeSubscriptionID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeSubID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByUser = `-- name: GetSubscriptionByUser :one
SELECT id, user_id, plan, status, current_period_end, stripe_customer_id, stripe_subscription_id, created_at, updated_at FROM subscriptions WHERE user_id = $1
`

func (q *Queries) GetSubscriptionByUser(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUser, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one

INSERT INTO subscriptions (
    id,
    user_id,
    plan,
    status,
    current_period_end,
    stripe_customer_id,
    stripe_subscription_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id) DO UPDATE SET
    plan                   = EXCLUDED.plan,
    status                 = EXCLUDED.status,
    current_period_end     = EXCLUDED.current_period_end,
    stripe_customer_id     = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id
RETURNING id, user_id, plan, status, current_period_end, stripe_customer_id, stripe_subscription_id, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Plan                 string             `json:"plan"`
	Status               string             `json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
}

// Subscriptions queries are defined but unused until billing ships. Keeping them
// here so the EntitlementChecker implementation has a ready-to-go data access
// layer when Stripe is wired up.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.ID,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.CurrentPeriodEnd,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
