// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, auth0_sub, email, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, auth0_sub, email, display_name, created_at, updated_at
`

type CreateUserParams struct {
	ID          uuid.UUID   `json:"id"`
	Auth0Sub    string      `json:"auth0_sub"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Auth0Sub,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuth0Sub = `-- name: GetUserByAuth0Sub :one
SELECT id, auth0_sub, email, display_name, created_at, updated_at FROM users WHERE auth0_sub = $1
`

func (q *Queries) GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuth0Sub, auth0Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth0_sub, email, display_name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email        = $2,
    display_name = $3
WHERE id = $1
RETURNING id, auth0_sub, email, display_name, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID   `json:"id"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByAuth0Sub = `-- name: UpsertUserByAuth0Sub :one
INSERT INTO users (id, auth0_sub, email, display_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth0_sub) DO UPDATE SET
    email        = EXCLUDED.email,
    display_name = EXCLUDED.display_name
RETURNING id, auth0_sub, email, display_name, created_at, updated_at
`

type UpsertUserByAuth0SubParams struct {
	ID          uuid.UUID   `json:"id"`
	Auth0Sub    string      `json:"auth0_sub"`
	Email       pgtype.Text `json:"email"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpsertUserByAuth0Sub(ctx context.Context, arg UpsertUserByAuth0SubParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByAuth0Sub,
		arg.ID,
		arg.Auth0Sub,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Auth0Sub,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
